
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git gitfast)

# User configuration
export PATH=$HOME/bin:/usr/local/bin:$PATH

# 提供一个方式，可以修改 oh-my-zsh 的配置
[[ -s $HOME/.zshrc.before ]] && source $HOME/.zshrc.before

source $ZSH/oh-my-zsh.sh

[[ -s $HOME/.autojump/etc/profile.d/autojump.sh ]] && source $HOME/.autojump/etc/profile.d/autojump.sh

function open_foler_path()
{
	local os_type_local="${1}"
	local folder_path="${2}"

        case ${os_type_local} in
            linux*)
                xdg-open "${folder_path}"
                ;;
            darwin*)
                open "${folder_path}"
                ;;
            cygwin)
		folder_path=$(cygpath -w -a ${folder_path})
		echo "$folder_path"
                #cygstart "" "$folder_path"
		cygstart explorer "$folder_path"
                ;;
            *)
                echo "Unknown operating system: ${os_type_local}" 1>&2
                ;;
        esac
}

function joo() {
    	setopt localoptions noautonamedirs
	local cypath="${1}"
	if [ -z "${cypath}" ]; then
		cypath="$(pwd)"
	fi

	if [ ! -d "$cypath" ];then
		echo "$cypath is not directory or not exist"
		return
	fi

	open_foler_path "${OSTYPE}" "$cypath"
}


autoload -U compinit && compinit -u

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export EDITOR='vim'

[[ -s $HOME/.zshrc.local ]] && source $HOME/.zshrc.local
