
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

export EDITOR='vim'

[[ -s $HOME/.autojump/etc/profile.d/autojump.sh ]] && source $HOME/.autojump/etc/profile.d/autojump.sh


function joo() {
    	setopt localoptions noautonamedirs
	local cypath="${1}"
	if [ -z "${cypath}" ]; then
		cypath="$(pwd)"
	fi

	if [ ! -d "$cypath" ];then
		echo "$cypath is not directory or not exist"
		return
	fi

        case ${OSTYPE} in
            linux*)
                xdg-open "${cypath}"
                ;;
            darwin*)
                open "${cypath}"
                ;;
            cygwin)
		cypath=$(cygpath -w -a ${cypath})
		echo "$cypath"
                #cygstart "" "$cypath"
		explorer "$cypath"
                ;;
            *)
                echo "Unknown operating system: ${OSTYPE}" 1>&2
                ;;
        esac
}


autoload -U compinit && compinit -u


[[ -s $HOME/.zshrc.local ]] && source $HOME/.zshrc.local





